import { Book } from '@/app/_common/types/Book';
import { ReduxError, ReduxLoading } from '@/app/_common/types/Redux';
import { PayloadAction, createSlice } from '@reduxjs/toolkit';

type InitialState = {
  loading: ReduxLoading<InitialState>;
  errors: ReduxError<InitialState>;
  books: Book[];
};

const initialState: InitialState = {
  errors: {},
  loading: {},
  books: [
    {
      id: 1,
      title: 'The Effective Engineer',
      available: true,
      authors: ['Edmond Lau'],
      year: 2009,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'effective-engineer.png',
      featured: true,
      recentlyAdded: true,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 2,
      title: 'Built To Last',
      available: false,
      authors: ['Jim Collins', 'Jerry I. Porras'],
      year: 2001,
      categories: ['Business', 'Entrepreneurship'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'built-to-last.png',
      featured: true,
      recentlyAdded: true,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 3,
      title: 'The Lean Startup',
      available: true,
      authors: ['Eric Reis'],
      year: 2005,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'the-lean-startup.png',
      featured: true,
      recentlyAdded: true,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 4,
      title: 'Effective Python',
      available: true,
      authors: ['Diomidis Spinellis'],
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'effective-python.png',
      featured: true,
      recentlyAdded: true,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 5,
      title: 'Big Magic',
      available: true,
      authors: ['Elizabeth Gilbert'],
      year: 2014,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'big-magic.png',
      featured: true,
      recentlyAdded: true,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 6,
      title: 'Big Magic',
      available: true,
      authors: ['Elizabeth Gilbert'],
      year: 2014,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'effective-python.png',
      featured: false,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 7,
      title: 'The Effective Engineer',
      available: true,
      authors: ['Edmond Lau'],
      year: 2009,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'effective-engineer.png',
      featured: true,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 8,
      title: 'Built To Last',
      available: false,
      authors: ['Jim Collins', 'Jerry I. Porras'],
      year: 2001,
      categories: ['Business', 'Entrepreneurship'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'built-to-last.png',
      featured: false,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 9,
      title: 'The Lean Startup',
      available: true,
      authors: ['Eric Reis'],
      year: 2005,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'the-lean-startup.png',
      featured: false,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 10,
      title: 'Effective Python',
      available: true,
      authors: ['Diomidis Spinellis'],
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'effective-python.png',
      featured: false,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 11,
      title: 'Big Magic',
      available: true,
      authors: ['Elizabeth Gilbert'],
      year: 2014,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'big-magic.png',
      featured: true,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 12,
      title: 'Big Magic',
      available: true,
      authors: ['Elizabeth Gilbert'],
      year: 2014,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'effective-engineer.png',
      featured: true,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
    {
      id: 13,
      title: 'The Lean Startup',
      available: true,
      authors: ['Eric Reis'],
      year: 2005,
      categories: ['Motivational'],
      ratings: 4,
      readCount: 31,
      likes: 29,
      imageUrl: 'the-lean-startup.png',
      featured: false,
      recentlyAdded: false,
      labels: ['Creative', 'Self-help'],
    },
  ],
};

export const bookSlice = createSlice({
  name: 'books',
  initialState,
  reducers: {
    startLoading(state, action: PayloadAction<keyof InitialState>) {
      state.loading[action.payload] = true;
    },
    endLoading(state, action: PayloadAction<keyof InitialState>) {
      state.loading[action.payload] = false;
    },
    setError(
      state,
      action: PayloadAction<{ key: keyof InitialState; error: unknown }>
    ) {
      state.loading[action.payload.key] = false;
      state.errors[action.payload.key] = action.payload.error;
    },
    setBooks(state, action: { payload: InitialState['books'] }) {
      state.books = action.payload;
    },
  },
});

export default bookSlice.reducer;
